### ISSUE TITLE
also link Prod key

### ISSUE THREAD

**Issue by NormTurtle** [THZoria/NX_Firmware#3]
would be usefulll it linked prod keys.

**Comment by THZoria** [comment]
Hello
You can recover the keys on your own via LockPick, I do not provide any keys on my side, Nintendo is quite intransigent on the subject.

**Comment by NormTurtle** [comment]
sorry, but i do not own any nintendo device.
so i can't do what you said.
but i have prod_key.zip 18.0 somethign 
would that be usefull?

**Comment by THZoria** [comment]
Maybe, like I said I'm not taking any chances with Nintendo who have already blown up some of my github repo's.

**Comment by impeeza** [comment]
> sorry, but i do not own any nintendo device. so i can't do what you said. but i have prod_key.zip 18.0 somethign would that be usefull?

Keys are: device dependant and copyrighted material of big N so ask or sharing them is considered piracy, so please do not.

**Comment by impeeza** [comment]
And please close the issue

**Comment by zunstarx115** [comment]
Understood thank you so much
