### ISSUE TITLE
Will it break my picofly or hwfly boot into hekate? 

### ISSUE THREAD

**Issue by 1stdevfriend** [THZoria/NX_Firmware#7]
Consider me like a total noob, but for playing newer games i need to update my firmware using daybreak. 

The only thing i'm concerned about is that will it break my picofly flashing into hekate? 

I know this shouldn't happen cause we are not updating there but just for a safer side i'm asking this.

**Comment by impeeza** [comment]
this is not a support site, please go to discord or GBATemp.net.


Firmware does not anything to do with the modchip, so you can upgrade without worry.

please close the issue.

**Comment by 1stdevfriend** [comment]
Thanks! It worked like a charm!
