### ISSUE TITLE
FW 19.0.1

### ISSUE THREAD

**Issue by impeeza** [THZoria/NX_Firmware#8]
Hello there,  have you been able to get the new FW Release?

**Comment by rumla3434** [comment]
https://github.com/rumla3434/NX_Firmware/releases/tag/19.0.1

**Comment by rumla3434** [comment]
> Hello there, have you been able to get the new FW Release?

https://github.com/rumla3434/NX_Firmware/releases/tag/19.0.1

**Comment by impeeza** [comment]
Thanks a lot.
