### ISSUE TITLE
10.0.3 release has 12.0.3 zip

### ISSUE THREAD

**Issue by Yoti** [THZoria/NX_Firmware#9]
I didn't check ZIP content, but [10.0.3 release](https://github.com/THZoria/NX_Firmware/releases/tag/10.0.3) has [12.0.3 named zip](https://github.com/THZoria/NX_Firmware/releases/download/10.0.3/Firmware.12.0.3.zip) inside.

**Comment by impeeza** [comment]
And is bit to bit the same 12.0.3 file.

**Comment by impeeza** [comment]
good catch

**Comment by Yoti** [comment]
Just finished downloading files. Both of them has same hash `35cb46f7d2d609f7d056c22099d1c469`. According to another site it's 12.0.3. The hash for the real 10.0.3 must be `f15f82570701868246016616979147d8`.

**Comment by THZoria** [comment]
Yes, it's a mistake, but I've updated the release with the correct firmware.

**Comment by Yoti** [comment]
@THZoria your new ZIP (`Firmware.10.0.3.zip`) still has same MD5 as 12.0.3 release (`35cb46f7d2d609f7d056c22099d1c469`).

**Comment by THZoria** [comment]
This time it should be good with the right hash f15f82570701868246016616979147d8

**Comment by Yoti** [comment]
Fixed.
